const mongoose = require('mongoose');

const ledgerEntrySchema = new mongoose.Schema(
  {
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Customer',
      required: [true, 'Customer ID is required'],
    },
    date: {
      type: String, // YYYY-MM-DD — timezone-safe string, never a Date object
      required: [true, 'Date is required'],
    },
    amount: {
      type: Number,
      required: [true, 'Amount is required'],
      min: [0, 'Amount cannot be negative'],
    },
    type: {
      type: String,
      enum: {
        values: ['debit', 'credit'],
        message: 'Type must be either debit or credit',
      },
      required: [true, 'Entry type is required'],
    },
    isAuto: {
      type: Boolean,
      default: false, // true = generated by cron/fallback; false = manually added
    },
    isDeleted: {
      type: Boolean,
      default: false, // Soft delete — never permanently remove records
    },
    notes: {
      type: String,
      default: '',
      trim: true,
    },
    // Audit trail for edited entries
    editHistory: [
      {
        editedAt: { type: Date, default: Date.now },
        previousAmount: Number,
        previousType: String,
        previousNotes: String,
      },
    ],
  },
  { timestamps: true }
);

// Compound index: fast lookup per customer per date
ledgerEntrySchema.index({ customerId: 1, date: -1 });
ledgerEntrySchema.index({ customerId: 1, date: 1, isDeleted: 1 });

module.exports = mongoose.model('LedgerEntry', ledgerEntrySchema);
